version: '3.1'

services:
  db:
    container_name: mysql-client-db
    image: mysql:8.0.31
    volumes:
      - dbbase:/var/lib/mysql
    ports:
      - "3308:3306"  
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hotel_client_db

volumes:
  dbbase: