# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    container_name: mysql_client_db
    image: mysql:8.0.31
    volumes:
      - dbbase:/var/lib/mysql
    ports:
      - "3308:3306"  
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hotel_client_db

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-client

    depends_on:
      - db
    ports:
      - 8001:80

volumes:
  dbbase:
